use kabu_shared::models::*;
use specta::ts::{self, ExportConfiguration};

fn main() {
    let config = ExportConfiguration::default();

    let types = [
        ts::export::<Stock>(&config),
        ts::export::<CreateStock>(&config),
        ts::export::<UpdateStock>(&config),
        ts::export::<Price>(&config),
        ts::export::<Transaction>(&config),
        ts::export::<PortfolioSummary>(&config),
        ts::export::<HoldingSummary>(&config),
    ];

    let mut output = String::from("// Auto-generated by kabu-typegen — do not edit manually\n\n");

    for result in types {
        match result {
            Ok(ts_type) => {
                output.push_str(&ts_type);
                output.push_str("\n\n");
            }
            Err(e) => {
                eprintln!("Error exporting type: {}", e);
                std::process::exit(1);
            }
        }
    }

    let out_path = "frontend/src/api/types.ts";
    std::fs::write(out_path, output).expect("Failed to write types.ts");
    println!("Types exported to {}", out_path);
}
