// Auto-generated by kabu-typegen — do not edit manually

export type Stock = { id: number; symbol: string; name: string | null; quantity: number; cost_basis: number; asset_type: string; created_at: string; updated_at: string }

export type CreateStock = { symbol: string; name: string | null; quantity: number; cost_basis: number; asset_type?: string }

export type UpdateStock = { name: string | null; quantity: number; cost_basis: number }

export type Price = { id: number; symbol: string; price: number; change: number | null; change_percent: number | null; high: number | null; low: number | null; open: number | null; previous_close: number | null; timestamp: string }

export type Transaction = { id: number; symbol: string; transaction_type: string; quantity: number; price: number; total_amount: number; transaction_date: string | null; source: string | null; raw_text: string | null; created_at: string }

export type PortfolioSummary = { total_cost: number; total_value: number; total_gain_loss: number; total_gain_loss_percent: number; holdings: HoldingSummary[] }

export type HoldingSummary = { stock: Stock; latest_price: number | null; current_value: number; gain_loss: number; gain_loss_percent: number }

export type ExchangeRate = { id: number; base: string; currency: string; rate: number; timestamp: string }

